apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: php-apache
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
